#!/usr/bin/env zsh

. $ZDOTDIR/plugins/fzf/conf.zsh

cmd="fd -H --ignore-file $XDG_CONFIG_HOME/fd/fdignore -L --strip-cwd-prefix --one-file-system -t d -p --base-directory $HOME ."
dir="$(eval "$cmd" | fzf-tmux --prompt="✨ " --cycle -p 50% --preview 'tree -C $HOME/{} | head -200' --reverse --history=$XDG_CACHE_DIR/fzf/dir_history --history-size=1000000000)"
dir="$(echo "$dir" | sed 's/\/$//')"

if [[ -n "$dir" ]]; then
    ta "$HOME/$dir"
fi
