#! /usr/bin/env zsh

# TODO Good Lord, this needs to be cleaned up. It _does_ work now, so there's that...

direction="$@"

log="$HOME/log"

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

cur_window_is_tmux() {
  hyprctl activewindow | grep -q "title: tmux -"
}

case $direction in
  "l")
    vimkeys="C-h"
    pane_cmd="-L"
    ;;
  "d")
    vimkeys="C-j"
    pane_cmd="-D"
    ;;
  "u")
    vimkeys="C-k"
    pane_cmd="-U"
    ;;
  "r")
    vimkeys="C-l"
    pane_cmd="-R"
    ;;
  *)
    >&2 echo "Unrecognized direction"
    ;;
esac

cur_pane_is_edge() {
  case $direction in
  "l")
    [[ $(tmux display-message -c $client_id -p '#{pane_at_left}') == 1 ]]
    ;;
  "d")
    [[ $(tmux display-message -c $client_id -p '#{pane_at_bottom}') == 1 ]]
    ;;
  "u")
    [[ $(tmux display-message -c $client_id -p '#{pane_at_top}') == 1 ]]
    ;;
  "r")
    [[ $(tmux display-message -c $client_id -p '#{pane_at_right}') == 1 ]]
    ;;
   *)
     >&2 echo "Unrecognized direction"
     ;;
 esac
}

if cur_window_is_tmux; then
  client_id="$(hyprctl activewindow | grep 'title: ' | awk -F ':' '{print $NF}')"
  pane_id="$(tmux display-message -c $client_id -p '#{pane_id}')"
  if cur_pane_is_edge; then
    hyprctl dispatch movefocus $direction
  else
    tmux if-shell "$is_vim" "send-keys -t '$pane_id' '$vimkeys'" "select-pane -t '$pane_id' '$pane_cmd'"
  fi
else
  hyprctl dispatch movefocus $direction
fi

exit 0
