#!/usr/bin/env bash

set -eu

# Constants
tag=bright_tag
icon_high="audio-volume-high"
icon_medium="audio-volume-medium"
icon_low="audio-volume-low"
icon_muted="audio-volume-muted"
icon_error="dialog-error" # New icon for error message
volume_step=5

time_delta=30
cache_file="/tmp/volume_id"

# Check for dependencies
if ! command -v wpctl >/dev/null || ! command -v notify-send >/dev/null; then
	logger -t volume_control "Required commands (wpctl and/or notify-send) not found. Exiting."
	exit 1
fi

# Function to handle errors and show an error notification
handle_error() {
	notify-send --app-name="System notification" --icon="$icon_error" -u critical -h string:x-dunst-stack-tag:"$tag" -h int:value:"0%" "Volume Control Error" "Error adjusting volume"
	logger -t volume_control "Error adjusting volume"
	exit 1
}

# Trap errors and call the error handling function
trap 'handle_error' ERR

# Argument handling
if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <increase|decrease|mute>" >&2
	exit 1
fi

case $1 in
increase)
	wpctl set-volume @DEFAULT_AUDIO_SINK@ ${volume_step}%+
	wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
	;;
decrease)
	wpctl set-volume @DEFAULT_AUDIO_SINK@ ${volume_step}%-
	wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
	;;
mute)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
	;;
*)
	echo "Invalid argument: $1. Use 'increase,' 'decrease,' or 'mute'." >&2
	exit 1
	;;
esac

# Get the current volume using wpctl
cur_vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
muted=0

if echo "$cur_vol" | grep -q "MUTED"; then
	muted=1
	cur_vol=$(echo $cur_vol | cut -d " " -f 2)
fi

percentage_normed=$(echo "$cur_vol" | cut -d ':' -f 2)
percentage=$(echo "($percentage_normed * 100)/1" | bc)

# Determine the appropriate icon
if [[ $muted == 1 ]]; then
	icon=${icon_muted}
elif [[ $percentage -ge 67 ]]; then
	icon=${icon_high}
elif [[ $percentage -ge 34 ]]; then
	icon=${icon_medium}
else
	icon=${icon_low}
fi

if ! [ -e "$cache_file" ] || [ "$(find "$cache_file" -mmin +$time_delta)" ]; then
	notify-send --app-name="System notification" --icon="$icon" -h int:value:"${percentage}%" "Volume" "${percentage}%" -p >$cache_file
else
	id=$(<"$cache_file")
	notify-send --app-name="System notification" --icon="$icon" -h int:value:"${percentage}%" "Volume" "${percentage}%" -r $id
fi

# notify-send --app-name="System notification" --icon="$icon" -h string:x-dunst-stack-tag:$tag -h int:value:"${percentage}%" "Volume" "${percentage}%"

exit 0
