set -g default-terminal "tmux-256color"
# Enable truecolor and underline extensions where supported.
set -ga terminal-overrides ',*:Tc'
set -as terminal-features ",tmux-256color*:RGB:usstyle:cstyle:ccolor:sync"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors - needs tmux-3.0

set-option -g status-style fg=default
set-window-option -g window-status-style bg=default
set-window-option -g window-status-current-style bg=default,bold

source-file $XDG_CONFIG_HOME/tmux/conf/options.conf
source-file $XDG_CONFIG_HOME/tmux/conf/keybinds.conf

# Plugins: tmux-yank
set -g @yank_action 'copy-pipe-and-cancel'
set -g @yank_with_mouse on

# Plugins: tmux-easy-motion
set -g @easy-motion-prefix "Space"

# Plugins: tmux-thumbs
set -g @thumbs-hint-fg-color green
set -g @thumbs-fg-color black
set -g @thumbs-bg-color yellow
set -g @thumbs-contrast 1
set -g @thumbs-command 'echo -n {} | pbcopy'
set -g @thumbs-unique enabled
set -g @thumbs-key f

# Plugins: tmux-fzf-url
set -g @fzf-url-bind 'u'
set -g @fzf-url-fzf-options "$FZF_DEFAULT_OPTS"
set -g @fzf-url-history-limit '2000'

# Plugins: tmux-easy-motion colors
set -g @easy-motion-dim-style "fg=#89b4fa"
set -g @easy-motion-highlight-style "fg=#f38ba8,bold"
set -g @easy-motion-highlight-2-first-style "fg=#a6e3a1,bold"
set -g @easy-motion-highlight-1-second-style "fg=#f38ba8,bold"

# Plugins list
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'IngoMeyer441/tmux-easy-motion'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tpm'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
